Nano aod cmssw 10 2 x
cms-nanoAOD/cmssw pull request #371
Opened 2019-05-21 09:27 UTC by dmajumder

#### PR description:

The previous DeepDoubleX tagger added to NanoAOD (PR#347) was for the mass-decorrelated version. 

This PR includes the non-decorrelated version in NanoAOD.

The non-mass-decorrelated version gives a better performance than the mass-correlated version:
https://indico.cern.ch/event/795581/contributions/3337046/attachments/1836661/3009499/CMS_HFW_Dubrovnik.pdf#page=12

Depending on the analysis selections, the user has a choice of either.

#### PR validation:

Tested in CMSSW_10_2_14 following the recipe in:
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3659/1.html

2019-08-22 14:39 UTC, peruzzim requested changes

2019-08-22 14:39 UTC, peruzzim commented on PhysicsTools/NanoAOD/python/jets_cff.py
> +        btag_DDBvL = Var("bDiscriminator('pfMassIndependentDeepDoubleBvLJetTags:probHbb')",float,doc="DeepDoubleX (mass-decorrelated) discriminator for H(Z)->bb vs QCD",precision=10),
Please revert this change to the names of the existing mass-decorrelated variables, it would be disruptive for people already using them.

2019-09-10 12:07 UTC, dmajumder commented
@peruzzim hope this is OK. 
BTW on the above comment for the DQM: 
"Please update PhysicsTools/NanoAOD/python/nanoDQM_cfi.py: take this patch or run prepareDQM.py -d -u nano_file_mc.root, and then if needed adjust the plot range using some human common sense."
What needs to be changed?

2019-09-20 12:06 UTC, peruzzim approved these changes

2019-09-20 12:06 UTC, merged