nanoAOD with proton information built in CMSSW_11_0_0_pre6
cms-nanoAOD/cmssw pull request #399
Opened 2019-09-20 15:25 UTC by jwill24

#### PR description:

This PR adds the proton information from PPS to the nanoAOD format. This is in response to the issue 332 raised back in May: https://github.com/cms-nanoAOD/cmssw/issues/332

#### PR validation:

This code has been tested on 2017 DoubleEG datasets for both SingleRP and MultiRP proton reconstruction.

#### if this PR is a backport please specify the original PR:

2019-09-23 11:28 UTC, peruzzim requested changes
a first set of comments

2019-09-23 11:28 UTC, peruzzim commented on PhysicsTools/NanoAOD/plugins/LHCInfoProducer.cc
> +    out->addColumnValue<float>("xangle", xangle, "LHC crossing angle", nanoaod::FlatTable::FloatColumn);
was precision forgotten here?

2019-09-23 11:28 UTC, peruzzim commented on PhysicsTools/NanoAOD/plugins/LHETablesProducer.cc
> +				    [this](const edm::InputTag& tag) { return mayConsume<LHEEventProduct>(tag); })),
please remove these spurious changes in indentation

2019-09-23 11:28 UTC, peruzzim commented on PhysicsTools/NanoAOD/plugins/ProtonProducer.cc
> +    produces<nanoaod::FlatTable>("trackTable");
let's use a more proton-specific name for this, please

2019-09-24 13:48 UTC, peruzzim commented
the code should do nothing when no PPS information is found in the event, please use mayConsume and test the validity of the handles when you get data from the event

2019-11-05 09:38 UTC, peruzzim commented
there is still something wrong here, @jwill24 can you please take a look?

2019-11-05 15:09 UTC, jwill24 commented
@peruzzim I checked the failure and it seems that it's an issue of the SimpleFlatTableProducer breaking the nanoSequence when proton information is not available. We discussed this previously and I thought I remember you saying that you could make the necessary changes to PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h since I do not have permission to edit this file. It should be as simple as adding an "isValid()" flag.

2019-12-09 15:01 UTC, jan-kaspar commented
@peruzzim I am confused by the status of this PR. Are we (PPS) expected to do something now or is your intervention the next step? Thanks in advance for clarification!

2020-01-15 11:12 UTC, peruzzim commented
following up on this now - sorry for the delay (no central production was missed because of this)

2020-02-19 12:08 UTC, peruzzim commented
My testing fails with a `No "LHCInfoRcd" record found in the EventSetup`

Is this supposed to work also on MC? Does it require specific content in the GT, or customization to the cfg to create this record in the event setup?

2020-02-19 12:30 UTC, jan-kaspar commented
> My testing fails with a `No "LHCInfoRcd" record found in the EventSetup`

LHCInfo should be in GT. Alternatively, you can use this tag: LHCInfoEndFill_prompt_v2

> Is this supposed to work also on MC? Does it require specific content in the GT, or customization to the cfg to create this record in the event setup?

PPS has no official simulation yet. Otherwise, from nanoAOD perspective, there should be no difference between data and simulation.

2020-02-19 12:40 UTC, peruzzim commented
> > My testing fails with a `No "LHCInfoRcd" record found in the EventSetup`
> 
> LHCInfo should be in GT. Alternatively, you can use this tag: LHCInfoEndFill_prompt_v2
> 

In which GTs should that payload be? In all of them (data and MC)? Was it added recently?

> > Is this supposed to work also on MC? Does it require specific content in the GT, or customization to the cfg to create this record in the event setup?
> 
> PPS has no official simulation yet. Otherwise, from nanoAOD perspective, there should be no difference between data and simulation.

Does this mean that all what is introduced by this PR is supposed to run only on data?

2020-02-19 12:52 UTC, jan-kaspar commented
> > > My testing fails with a `No "LHCInfoRcd" record found in the EventSetup`
> > 
> > 
> > LHCInfo should be in GT. Alternatively, you can use this tag: LHCInfoEndFill_prompt_v2
> 
> In which GTs should that payload be? In all of them (data and MC)? Was it added recently?

I have no idea about MC tags.

It should be in data GTs, it was introduced ~year ago. Here's an example I used for some recent proton reco tests:
  https://cms-conddb.cern.ch/cmsDbBrowser/search/Prod/106X_dataRun2_v26

> > > Is this supposed to work also on MC? Does it require specific content in the GT, or customization to the cfg to create this record in the event setup?
> > 
> > 
> > PPS has no official simulation yet. Otherwise, from nanoAOD perspective, there should be no difference between data and simulation.
> 
> Does this mean that all what is introduced by this PR is supposed to run only on data?

At this moment, it can only be useful with data.

2020-02-19 13:09 UTC, peruzzim commented
thank you, I will apply some modifications and limit my tests to data

2020-02-19 13:12 UTC, jan-kaspar commented
> thank you, I will apply some modifications and limit my tests to data

Thanks to you!

2020-02-21 12:52 UTC, peruzzim commented
replaced by #504, with refactor code

2020-02-21 12:52 UTC, closed without merging